=== cubux-net/web-v2-i18n/schemas/front/budget.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "string": {
      "type": "string",
      "minLength": 1
    }
  },
  "type": "object",
  "properties": {
    "entry": {
      "type": "object",
      "properties": {
        "loop": {
          "type": "object",
          "properties": {
            "Month": {
              "$ref": "#/$defs/string"
            },
            "Year": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Month", "Year"]
        },
        "message": {
          "type": "object",
          "properties": {
            "AssignCategoriesByEdit": {
              "$ref": "#/$defs/string"
            },
            "DeleteConfirm": {
              "$ref": "#/$defs/string"
            },
            "NoCategoriesAssignedToShowFacts": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "AssignCategoriesByEdit",
            "DeleteConfirm",
            "NoCategoriesAssignedToShowFacts"
          ]
        },
        "property": {
          "type": "object",
          "properties": {
            "Loop": {
              "$ref": "#/$defs/string"
            },
            "Name": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Loop", "Name"]
        },
        "title": {
          "type": "object",
          "properties": {
            "Create": {
              "$ref": "#/$defs/string"
            },
            "Delete": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Create", "Delete"]
        },
        "type": {
          "type": "object",
          "properties": {
            "Expense": {
              "$ref": "#/$defs/string"
            },
            "Income": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Expense", "Income"]
        },
        "validation": {
          "type": "object",
          "properties": {
            "EndDateAfterStartDate": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["EndDateAfterStartDate"]
        }
      },
      "required": ["loop", "message", "property", "title", "type", "validation"]
    },
    "page": {
      "type": "object",
      "properties": {
        "Title": {
          "$ref": "#/$defs/string"
        },
        "label": {
          "type": "object",
          "properties": {
            "Budgets": {
              "$ref": "#/$defs/string"
            },
            "Difference": {
              "$ref": "#/$defs/string"
            },
            "ExpensesByCategories": {
              "$ref": "#/$defs/string"
            },
            "Fact": {
              "$ref": "#/$defs/string"
            },
            "IncomesByCategories": {
              "$ref": "#/$defs/string"
            },
            "Plan": {
              "$ref": "#/$defs/string"
            },
            "Progress": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "Budgets",
            "Difference",
            "ExpensesByCategories",
            "Fact",
            "IncomesByCategories",
            "Plan",
            "Progress"
          ]
        }
      },
      "required": ["Title", "label"]
    },
    "period": {
      "type": "object",
      "properties": {
        "property": {
          "type": "object",
          "properties": {
            "Inherit": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Inherit"]
        }
      },
      "required": ["property"]
    },
    "timeline": {
      "type": "object",
      "properties": {
        "label": {
          "type": "object",
          "properties": {
            "ShowAllCategories": {
              "$ref": "#/$defs/string"
            },
            "Totals": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["ShowAllCategories", "Totals"]
        }
      },
      "required": ["label"]
    }
  },
  "required": ["entry", "page", "period", "timeline"]
}

=== cubux-net/web-v2-i18n/locales/el/front/budget.json
{
  "entry": {
    "loop": {
      "Month": "Για μήνα",
      "Year": "Για το έτος"
    },
    "message": {
      "AssignCategoriesByEdit": "Σχεδιασμός ορισμένων κατηγοριών με \"Επεξεργασία\" κουμπί.",
      "DeleteConfirm": "Είστε βέβαιοι να διαγράψετε αυτόν τον προϋπολογισμό?",
      "NoCategoriesAssignedToShowFacts": "Δεν υπάρχουν προγραμματισμένες κατηγορίες από τις οποίες θα εμφανίζονται οι λειτουργίες."
    },
    "property": {
      "Loop": "Περίοδος",
      "Name": "Όνομα"
    },
    "title": {
      "Create": "Προσθήκη προϋπολογισμού",
      "Delete": "Διαγραφή προϋπολογισμού"
    },
    "type": {
      "Expense": "Έξοδα",
      "Income": "Εισοδήματα"
    },
    "validation": {
      "EndDateAfterStartDate": "Η ημερομηνία λήξης πρέπει να είναι μεταγενέστερη της ημερομηνίας έναρξης"
    }
  },
  "page": {
    "label": {
      "Budgets": "Προϋπολογισμοί",
      "Difference": "Διαφορά",
      "ExpensesByCategories": "Δαπάνες ανά κατηγορίες προϋπολογισμού:",
      "Fact": "Fact",
      "IncomesByCategories": "Εισοδήματα ανά κατηγορία προϋπολογισμού:",
      "Plan": "Σχέδιο",
      "Progress": "Πρόοδος"
    },
    "Title": "Προϋπολογισμός"
  },
  "period": {
    "property": {
      "Inherit": "Για όλες τις μελλοντικές περιόδους"
    }
  },
  "timeline": {
    "label": {
      "ShowAllCategories": "Εμφάνιση όλων",
      "Totals": "Σύνολο"
    }
  }
}

=== cubux-net/web-v2-i18n/locales/cs/front/budget.json
{
  "entry": {
    "loop": {
      "Month": "Na měsíc",
      "Year": "Na rok"
    },
    "message": {
      "AssignCategoriesByEdit": "Naplánujte Kategorie pomocí tlačítka \"Upravit\".",
      "DeleteConfirm": "Opravdu chcete tento rozpočet smazat?",
      "NoCategoriesAssignedToShowFacts": "Žádné plánované kategorie pro zobrazení operací."
    },
    "property": {
      "Loop": "Období",
      "Name": "Název"
    },
    "title": {
      "Create": "Přidat rozpočet",
      "Delete": "Odstranit rozpočet"
    },
    "type": {
      "Expense": "Výdaje",
      "Income": "Příjmy"
    },
    "validation": {
      "EndDateAfterStartDate": "Datum ukončení by mělo být později než datum zahájení."
    }
  },
  "page": {
    "label": {
      "Budgets": "Rozpočet",
      "Difference": "Rozdíl",
      "ExpensesByCategories": "Výdaje podle rozpočtových kategorií:",
      "Fact": "Skutečnost",
      "IncomesByCategories": "Příjmy podle rozpočtových kategorií:",
      "Plan": "Plán",
      "Progress": "Provedení"
    },
    "Title": "Rozpočet"
  },
  "period": {
    "property": {
      "Inherit": "Pro všechny budoucí data"
    }
  },
  "timeline": {
    "label": {
      "ShowAllCategories": "Zobrazit vše",
      "Totals": "Celkem"
    }
  }
}

=== cubux-net/web-v2-i18n/locales/en/front/budget.json
{
  "entry": {
    "loop": {
      "Month": "For month",
      "Year": "For year"
    },
    "message": {
      "AssignCategoriesByEdit": "Plan some categories with \"Edit\" button.",
      "DeleteConfirm": "Are you sure to delete this budget?",
      "NoCategoriesAssignedToShowFacts": "No planned categories to show operations from."
    },
    "property": {
      "Loop": "Period",
      "Name": "Name"
    },
    "title": {
      "Create": "Add budget",
      "Delete": "Delete budget"
    },
    "type": {
      "Expense": "Expenses",
      "Income": "Incomes"
    },
    "validation": {
      "EndDateAfterStartDate": "End date must be after start date"
    }
  },
  "page": {
    "label": {
      "Budgets": "Budgets",
      "Difference": "Difference",
      "ExpensesByCategories": "Expenses by budget categories:",
      "Fact": "Fact",
      "IncomesByCategories": "Incomes by budget categories:",
      "Plan": "Plan",
      "Progress": "Progress"
    },
    "Title": "Budget"
  },
  "period": {
    "property": {
      "Inherit": "For all future periods"
    }
  },
  "timeline": {
    "label": {
      "ShowAllCategories": "Show all",
      "Totals": "Total"
    }
  }
}

=== cubux-net/web-v2-i18n/locales/ru/front/budget.json
{
  "entry": {
    "loop": {
      "Month": "На месяц",
      "Year": "На год"
    },
    "message": {
      "AssignCategoriesByEdit": "Запланируйте категории с помощью кнопки \"Редактировать\".",
      "DeleteConfirm": "Вы действительно хотите удалить данный бюджет?",
      "NoCategoriesAssignedToShowFacts": "Нет запланированных категорий, чтобы показать операции."
    },
    "property": {
      "Loop": "Период",
      "Name": "Название"
    },
    "title": {
      "Create": "Добавить бюджет",
      "Delete": "Удалить бюджет"
    },
    "type": {
      "Expense": "Расходы",
      "Income": "Доходы"
    },
    "validation": {
      "EndDateAfterStartDate": "Дата окончания должна быть позже даты начала."
    }
  },
  "page": {
    "label": {
      "Budgets": "Бюджеты",
      "Difference": "Разница",
      "ExpensesByCategories": "Расходы по категориям бюджета:",
      "Fact": "Факт",
      "IncomesByCategories": "Доходы по категориям бюджета:",
      "Plan": "План",
      "Progress": "Выполнение"
    },
    "Title": "Бюджет"
  },
  "period": {
    "property": {
      "Inherit": "Для всех будущих дат"
    }
  },
  "timeline": {
    "label": {
      "ShowAllCategories": "Показать все",
      "Totals": "Итого"
    }
  }
}

=== cubux-net/web-v2-i18n/locales/uk/front/budget.json
{
  "entry": {
    "loop": {
      "Month": "На місяць",
      "Year": "На рік"
    },
    "message": {
      "AssignCategoriesByEdit": "Заплануйте категорії за допомогою кнопки \"Редагувати\".",
      "DeleteConfirm": "Ви справді хочете видалити цей бюджет?",
      "NoCategoriesAssignedToShowFacts": "Немає запланованих категорій, щоб відобразити операції."
    },
    "property": {
      "Loop": "Період",
      "Name": "Назва"
    },
    "title": {
      "Create": "Додати бюджет",
      "Delete": "Видалити бюджет"
    },
    "type": {
      "Expense": "Витрати",
      "Income": "Доходи"
    },
    "validation": {
      "EndDateAfterStartDate": "Дата закінчення мусить бути пізнішою, ніж дата початку."
    }
  },
  "page": {
    "label": {
      "Budgets": "Бюджети",
      "Difference": "Різниця",
      "ExpensesByCategories": "Витрати за категоріями бюджету:",
      "Fact": "Факт",
      "IncomesByCategories": "Доходи за категоріями бюджету:",
      "Plan": "План",
      "Progress": "Виконання"
    },
    "Title": "Бюджет"
  },
  "period": {
    "property": {
      "Inherit": "Для всіх майбутніх дат"
    }
  },
  "timeline": {
    "label": {
      "ShowAllCategories": "Показати все",
      "Totals": "Загальна сума"
    }
  }
}

=== cubux-net/web-v2-i18n/locales/es/front/budget.json
{
  "entry": {
    "loop": {
      "Month": "Por mes",
      "Year": "Por año"
    },
    "message": {
      "AssignCategoriesByEdit": "Planifique algunas categorías con \"Editar\" botón.",
      "DeleteConfirm": "¿Está seguro de eliminar este presupuesto?",
      "NoCategoriesAssignedToShowFacts": "No hay categorías planificadas para mostrar operaciones."
    },
    "property": {
      "Loop": "Período",
      "Name": "Nombre"
    },
    "title": {
      "Create": "Agregar presupuesto",
      "Delete": "Eliminar presupuesto"
    },
    "type": {
      "Expense": "Gastos",
      "Income": "Ingresos"
    },
    "validation": {
      "EndDateAfterStartDate": "fecha de finalización debe ser posterior a fecha de inicio."
    }
  },
  "page": {
    "label": {
      "Budgets": "Presupuestos",
      "Difference": "Diferencia",
      "ExpensesByCategories": "Gastos por categorías presupuestarias:",
      "Fact": "Hecho",
      "IncomesByCategories": "Ingresos por categorías presupuestarias:",
      "Plan": "Plan",
      "Progress": "Progreso"
    },
    "Title": "Presupuesto"
  },
  "period": {
    "property": {
      "Inherit": "Para todos los periodos futuros"
    }
  },
  "timeline": {
    "label": {
      "ShowAllCategories": "Mostrar todo",
      "Totals": "Total"
    }
  }
}
