=== cubux-net/web-v2-i18n/schemas/front/credits.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "string": {
      "type": "string",
      "minLength": 1
    }
  },
  "type": "object",
  "properties": {
    "button": {
      "type": "object",
      "properties": {
        "AddCredit": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["AddCredit"]
    },
    "error": {
      "type": "object",
      "properties": {
        "SomePlanChangedWasNotSaved": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["SomePlanChangedWasNotSaved"]
    },
    "form": {
      "type": "object",
      "properties": {
        "hint": {
          "type": "object",
          "properties": {
            "Duration": {
              "$ref": "#/$defs/string"
            },
            "FeeFromSyncAccountsAll": {
              "$ref": "#/$defs/string"
            },
            "FeeFromSyncAccountsSome": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "Duration",
            "FeeFromSyncAccountsAll",
            "FeeFromSyncAccountsSome"
          ]
        },
        "label": {
          "type": "object",
          "properties": {
            "Duration": {
              "$ref": "#/$defs/string"
            },
            "EndDate": {
              "$ref": "#/$defs/string"
            },
            "FeeFromAccounts": {
              "$ref": "#/$defs/string"
            },
            "Name": {
              "$ref": "#/$defs/string"
            },
            "OnlyCurrency": {
              "$ref": "#/$defs/string"
            },
            "PlanType": {
              "$ref": "#/$defs/string"
            },
            "Rate": {
              "$ref": "#/$defs/string"
            },
            "ReceiveCreditToAccount": {
              "$ref": "#/$defs/string"
            },
            "RemainToFee": {
              "$ref": "#/$defs/string"
            },
            "StartDate": {
              "$ref": "#/$defs/string"
            },
            "TotalCreditAmount": {
              "$ref": "#/$defs/string"
            },
            "TotalPayAmount": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "Duration",
            "EndDate",
            "FeeFromAccounts",
            "Name",
            "OnlyCurrency",
            "PlanType",
            "Rate",
            "ReceiveCreditToAccount",
            "RemainToFee",
            "StartDate",
            "TotalCreditAmount",
            "TotalPayAmount"
          ]
        },
        "planType": {
          "type": "object",
          "properties": {
            "Ann": {
              "$ref": "#/$defs/string"
            },
            "Diff": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Ann", "Diff"]
        },
        "title": {
          "type": "object",
          "properties": {
            "CreateCredit": {
              "$ref": "#/$defs/string"
            },
            "EditCredit": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["CreateCredit", "EditCredit"]
        }
      },
      "required": ["hint", "label", "planType", "title"]
    },
    "formOperation": {
      "type": "object",
      "properties": {
        "label": {
          "type": "object",
          "properties": {
            "DealWithAccounts": {
              "$ref": "#/$defs/string"
            },
            "LinkToPlan": {
              "$ref": "#/$defs/string"
            },
            "LinkToPlanItem": {
              "$ref": "#/$defs/string"
            },
            "NoLinkToPlan": {
              "$ref": "#/$defs/string"
            },
            "SelectTransaction": {
              "$ref": "#/$defs/string"
            },
            "TransactionLinked": {
              "$ref": "#/$defs/string"
            },
            "TransactionNotLinked": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "DealWithAccounts",
            "LinkToPlan",
            "LinkToPlanItem",
            "NoLinkToPlan",
            "SelectTransaction",
            "TransactionLinked",
            "TransactionNotLinked"
          ]
        },
        "message": {
          "type": "object",
          "properties": {
            "SelectTransaction": {
              "$ref": "#/$defs/string"
            },
            "TransactionFetchFailed": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["SelectTransaction", "TransactionFetchFailed"]
        }
      },
      "required": ["label", "message"]
    },
    "formPlan": {
      "type": "object",
      "properties": {
        "label": {
          "type": "object",
          "properties": {
            "PaidAmount": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["PaidAmount"]
        },
        "title": {
          "type": "object",
          "properties": {
            "CreatePlan": {
              "$ref": "#/$defs/string"
            },
            "EditPlan": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["CreatePlan", "EditPlan"]
        }
      },
      "required": ["label", "title"]
    },
    "page": {
      "type": "object",
      "properties": {
        "Title": {
          "$ref": "#/$defs/string"
        },
        "state": {
          "type": "object",
          "properties": {
            "Completed": {
              "$ref": "#/$defs/string"
            },
            "Pending": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Completed", "Pending"]
        }
      },
      "required": ["Title", "state"]
    },
    "pageItem": {
      "type": "object",
      "properties": {
        "button": {
          "type": "object",
          "properties": {
            "DeleteKeepTransaction": {
              "$ref": "#/$defs/string"
            },
            "DeleteWithTransaction": {
              "$ref": "#/$defs/string"
            },
            "Finish": {
              "$ref": "#/$defs/string"
            },
            "PayNow": {
              "$ref": "#/$defs/string"
            },
            "UndoFinish": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "DeleteKeepTransaction",
            "DeleteWithTransaction",
            "Finish",
            "PayNow",
            "UndoFinish"
          ]
        },
        "label": {
          "type": "object",
          "properties": {
            "AlreadyPaidAmount": {
              "$ref": "#/$defs/string"
            },
            "CreatePayCalendar": {
              "$ref": "#/$defs/string"
            },
            "NextPayment": {
              "$ref": "#/$defs/string"
            },
            "ViewPayCalendar": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "AlreadyPaidAmount",
            "CreatePayCalendar",
            "NextPayment",
            "ViewPayCalendar"
          ]
        },
        "message": {
          "type": "object",
          "properties": {
            "ConfirmDelete": {
              "$ref": "#/$defs/string"
            },
            "ConfirmDeleteMayKeepTransaction": {
              "$ref": "#/$defs/string"
            },
            "ConfirmFinish": {
              "$ref": "#/$defs/string"
            },
            "ConfirmUndoFinish": {
              "$ref": "#/$defs/string"
            },
            "DeleteConfirm": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "ConfirmDelete",
            "ConfirmDeleteMayKeepTransaction",
            "ConfirmFinish",
            "ConfirmUndoFinish",
            "DeleteConfirm"
          ]
        },
        "title": {
          "type": "object",
          "properties": {
            "DeleteCredit": {
              "$ref": "#/$defs/string"
            },
            "Operations": {
              "$ref": "#/$defs/string"
            },
            "PaymentsChart": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["DeleteCredit", "Operations", "PaymentsChart"]
        }
      },
      "required": ["button", "label", "message", "title"]
    }
  },
  "required": [
    "button",
    "error",
    "form",
    "formOperation",
    "formPlan",
    "page",
    "pageItem"
  ]
}

=== cubux-net/web-v2-i18n/locales/cs/front/credits.json
{
  "button": {
    "AddCredit": "Přidat\nÚvěr"
  },
  "error": {
    "SomePlanChangedWasNotSaved": "Některé změny nebylo možné uložit kvůli chybám."
  },
  "form": {
    "hint": {
      "Duration": "Měsíce",
      "FeeFromSyncAccountsAll": "Automatické platby nebudou fungovat pro synchronizované účty.",
      "FeeFromSyncAccountsSome": "Automatické platby nebudou fungovat pro synchronizované účty."
    },
    "label": {
      "Duration": "Období",
      "EndDate": "Datum ukončení",
      "FeeFromAccounts": "Platit automaticky z účtů",
      "Name": "Název",
      "OnlyCurrency": "Nezapočítat na účet",
      "PlanType": "Typ splátek",
      "Rate": "Úrokova sazba",
      "ReceiveCreditToAccount": "Připsat na účet",
      "RemainToFee": "Zbývá splatit",
      "StartDate": "Datum začátku",
      "TotalCreditAmount": "Přijatá částka",
      "TotalPayAmount": "Celková částka plateb"
    },
    "planType": {
      "Ann": "Anuitní",
      "Diff": "Diferencovaný"
    },
    "title": {
      "CreateCredit": "Přidat úvěr",
      "EditCredit": "Upravit úvěr"
    }
  },
  "formOperation": {
    "label": {
      "DealWithAccounts": "Ovlivňuje zůstatky na účtu",
      "LinkToPlan": "Vázat na splátkový kalendář",
      "LinkToPlanItem": "{date}: {paid} {ofTotal} ({percent}%)",
      "NoLinkToPlan": "mimo plán výplaty",
      "SelectTransaction": "Vyberte transakci...",
      "TransactionLinked": "Vázaná transakce ve výši {amount} za {date}{ifAccountValid, select, 0{ z jiného účtu} other{}}",
      "TransactionNotLinked": "Transakce není vázána"
    },
    "message": {
      "SelectTransaction": "Zadejte transakci.",
      "TransactionFetchFailed": "Nepodařilo se získat podrobnosti o vybrané transakci."
    }
  },
  "formPlan": {
    "label": {
      "Amount": "Částka",
      "Date": "Datum",
      "PaidAmount": "Splaceno"
    },
    "title": {
      "CreatePlan": "Vytvořte si výplatní kalendář",
      "EditPlan": "Upravit výplatní kalendář"
    }
  },
  "page": {
    "state": {
      "Completed": "Splaceno",
      "Pending": "Aktualní"
    },
    "Title": "Úvěry"
  },
  "pageItem": {
    "button": {
      "DeleteKeepTransaction": "Smazat, ale ponechat transakce",
      "DeleteWithTransaction": "Smazat spolu s transakcí",
      "Finish": "Dokončit",
      "PayNow": "Zaplatit teď",
      "UndoFinish": "Storno dokončení"
    },
    "label": {
      "AlreadyPaidAmount": "Splaceno",
      "CreatePayCalendar": "Vytvořte si výplatní kalendář",
      "NextPayment": "Další splátka",
      "ViewPayCalendar": "Zobrazit výplatní kalendář"
    },
    "message": {
      "ConfirmDelete": "Opravdu chcete smazat úvěrovou transakci? Zůstatky na účtu nebudou ovlivněny.",
      "ConfirmDeleteMayKeepTransaction": "Tato úvěrová operace je spojena s transakcí. Při smazání této úvěrovou operace můžete transakci buď nechat, nebo ji smazat.",
      "ConfirmFinish": "Dokončit úvěr?",
      "ConfirmUndoFinish": "Storno dokončení úvěru?",
      "DeleteConfirm": "Opravdu chcete tento úvěr smazat?"
    },
    "title": {
      "DeleteCredit": "Odstranění Úvěru",
      "Operations": "Historie operací",
      "PaymentsChart": "Splátkový kalendář"
    }
  }
}

=== cubux-net/web-v2-i18n/locales/ru/front/credits.json
{
  "button": {
    "AddCredit": "Добавить\nКредит"
  },
  "error": {
    "SomePlanChangedWasNotSaved": "Некоторые изменения не удалось сохранить из-за ошибок."
  },
  "form": {
    "hint": {
      "Duration": "Месяцев",
      "FeeFromSyncAccountsAll": "Автоматические платежи не будут работать для синхронизированных счетов.",
      "FeeFromSyncAccountsSome": "Автоматические платежи не будут работать для синхронизированных счетов."
    },
    "label": {
      "Duration": "Срок",
      "EndDate": "Дата окончания",
      "FeeFromAccounts": "Выплачивать автоматически со счетов",
      "Name": "Название",
      "OnlyCurrency": "Не зачислять на счёт",
      "PlanType": "Тип выплат",
      "Rate": "Ставка",
      "ReceiveCreditToAccount": "Зачислить на счёт",
      "RemainToFee": "Осталось выплатить",
      "StartDate": "Дата начала",
      "TotalCreditAmount": "Полученная сумма",
      "TotalPayAmount": "Общая сумма выплат"
    },
    "planType": {
      "Ann": "Аннуитетный",
      "Diff": "Дифференцированный"
    },
    "title": {
      "CreateCredit": "Добавить кредит",
      "EditCredit": "Изменить кредит"
    }
  },
  "formOperation": {
    "label": {
      "DealWithAccounts": "Влияет на остатки на счетах",
      "LinkToPlan": "Привязать к графику",
      "LinkToPlanItem": "{date}: {paid} {ofTotal} ({percent}%)",
      "NoLinkToPlan": "вне плана",
      "SelectTransaction": "Выберите транзакцию...",
      "TransactionLinked": "Привязана транзакция на {amount} за {date}{ifAccountValid, select, 0{ по другому счёту} other{}}",
      "TransactionNotLinked": "Транзакция не привязана"
    },
    "message": {
      "SelectTransaction": "Укажите транзакцию.",
      "TransactionFetchFailed": "Не удалось получить детали по выбранной транзакции."
    }
  },
  "formPlan": {
    "label": {
      "PaidAmount": "Выплачено"
    },
    "title": {
      "CreatePlan": "Создать календарь выплат",
      "EditPlan": "Изменить календарь выплат"
    }
  },
  "page": {
    "state": {
      "Completed": "Выплаченные",
      "Pending": "Актуальные"
    },
    "Title": "Кредиты"
  },
  "pageItem": {
    "button": {
      "DeleteKeepTransaction": "Удалить, но оставить транзакцию",
      "DeleteWithTransaction": "Удалить вместе с транзакцией",
      "Finish": "Завершить",
      "PayNow": "Заплатить сейчас",
      "UndoFinish": "Отменить завершение"
    },
    "label": {
      "AlreadyPaidAmount": "Выплачено",
      "CreatePayCalendar": "Создать календарь выплат",
      "NextPayment": "Следующий платёж",
      "ViewPayCalendar": "Посмотреть календарь выплат"
    },
    "message": {
      "ConfirmDelete": "Вы уверены, что хотите удалить кредитную операцию? Это не затронет остатки на счетах.",
      "ConfirmDeleteMayKeepTransaction": "Эта кредитная операция связана с транзакцией. При удалении этой кредитной операции вы можете как оставить транзакцию, так и удалить её.",
      "ConfirmFinish": "Завершить кредит?",
      "ConfirmUndoFinish": "Отменить завершение кредита?",
      "DeleteConfirm": "Вы уверены, что хотите удалить этот кредит?"
    },
    "title": {
      "DeleteCredit": "Удаление Кредита",
      "Operations": "История операций",
      "PaymentsChart": "График платежей"
    }
  }
}

=== cubux-net/web-v2-i18n/locales/en/front/credits.json
{
  "button": {
    "AddCredit": "Add\nCredit"
  },
  "error": {
    "SomePlanChangedWasNotSaved": "Some changes was not saved due to errors."
  },
  "form": {
    "hint": {
      "Duration": "Months",
      "FeeFromSyncAccountsAll": "Automated payment will not work with synchronized accounts.",
      "FeeFromSyncAccountsSome": "Automated payment will not work with synchronized accounts."
    },
    "label": {
      "Duration": "Duration",
      "EndDate": "End date",
      "FeeFromAccounts": "Pay automatically from accounts",
      "Name": "Name",
      "OnlyCurrency": "Don't add to account",
      "PlanType": "Plan type",
      "Rate": "Rate",
      "ReceiveCreditToAccount": "Receive credit to account",
      "RemainToFee": "Remain to fee",
      "StartDate": "Start date",
      "TotalCreditAmount": "Total credit amount",
      "TotalPayAmount": "Total pay amount"
    },
    "planType": {
      "Ann": "Annuity",
      "Diff": "Differential"
    },
    "title": {
      "CreateCredit": "Add credit",
      "EditCredit": "Edit credit"
    }
  },
  "formOperation": {
    "label": {
      "DealWithAccounts": "Does affect accounts",
      "LinkToPlan": "Link to plan",
      "LinkToPlanItem": "{date}: {paid} {ofTotal} ({percent}%)",
      "NoLinkToPlan": "out of plan",
      "SelectTransaction": "Select transaction...",
      "TransactionLinked": "Linked transaction for {amount} at {date}{ifAccountValid, select, 0{ with another account} other{}}",
      "TransactionNotLinked": "No transaction linked"
    },
    "message": {
      "SelectTransaction": "Please, select transaction.",
      "TransactionFetchFailed": "Could not fetch details for linked transaction."
    }
  },
  "formPlan": {
    "label": {
      "PaidAmount": "Paid"
    },
    "title": {
      "CreatePlan": "Create plan",
      "EditPlan": "Edit plan"
    }
  },
  "page": {
    "state": {
      "Completed": "Finished",
      "Pending": "Actual"
    },
    "Title": "Credits"
  },
  "pageItem": {
    "button": {
      "DeleteKeepTransaction": "Delete operation, keep transactions",
      "DeleteWithTransaction": "Delete WITH transaction",
      "Finish": "Complete",
      "PayNow": "Pay now",
      "UndoFinish": "Cancel completion"
    },
    "label": {
      "AlreadyPaidAmount": "Already paid",
      "CreatePayCalendar": "Create payments plan",
      "NextPayment": "Next payment",
      "ViewPayCalendar": "View payments plan"
    },
    "message": {
      "ConfirmDelete": "Are you sure to delete this credit operation? This action will not change accounts balance.",
      "ConfirmDeleteMayKeepTransaction": "This credit operation is linked with transaction. You can keep the transaction or delete it too while deleting credit operation.",
      "ConfirmFinish": "Complete credit?",
      "ConfirmUndoFinish": "Cancel credit completion?",
      "DeleteConfirm": "Are you sure to delete this credit completely?"
    },
    "title": {
      "DeleteCredit": "Deleting Credit",
      "Operations": "Operations history",
      "PaymentsChart": "Payments chart"
    }
  }
}

=== cubux-net/web-v2-i18n/locales/uk/front/credits.json
{
  "button": {
    "AddCredit": "Додати\nКредит"
  },
  "error": {
    "SomePlanChangedWasNotSaved": "Деякі зміни не вдалося зберегти через помилилки."
  },
  "form": {
    "hint": {
      "Duration": "Місяців",
      "FeeFromSyncAccountsAll": "Автоматичні платежі не будуть працювати для синхронізованих рахунків.",
      "FeeFromSyncAccountsSome": "Автоматичні платежі не будуть працювати для синхронізованих рахунків."
    },
    "label": {
      "Duration": "Термін",
      "EndDate": "Дата закінчення",
      "FeeFromAccounts": "Виплачувати автоматично з рахунків",
      "Name": "Назва",
      "OnlyCurrency": "Не переказувати на рахунок",
      "PlanType": "Тип виплат",
      "Rate": "Ставка",
      "ReceiveCreditToAccount": "Переказати на рахунок",
      "RemainToFee": "Залишилось сплатити",
      "StartDate": "Дата початку",
      "TotalCreditAmount": "Отримана сума",
      "TotalPayAmount": "Загальна сума виплат"
    },
    "planType": {
      "Ann": "Ануїтетна схема погашення",
      "Diff": "Диференційована схема погашення"
    },
    "title": {
      "CreateCredit": "Додати кредит",
      "EditCredit": "Редагувати кредит"
    }
  },
  "formOperation": {
    "label": {
      "DealWithAccounts": "Впливає на залишки на рахунках",
      "LinkToPlan": "Прив'язати до графіка виплат",
      "LinkToPlanItem": "{date}: {paid} {ofTotal} ({percent}%)",
      "NoLinkToPlan": "поза межами графіка виплат",
      "SelectTransaction": "Виберіть транзакцію...",
      "TransactionLinked": "Прив'язана транзакція на суму {amount} за {date}{ifAccountValid, select, 0{ по іншому рахунку} other{}}",
      "TransactionNotLinked": "Транзакція не прив'язана"
    },
    "message": {
      "SelectTransaction": "Виберіть транзакцию.",
      "TransactionFetchFailed": "Не вдалося отримати деталі за вибраною транзакцією."
    }
  },
  "formPlan": {
    "label": {
      "Amount": "Сума",
      "Date": "Дата",
      "PaidAmount": "Виплачено"
    },
    "title": {
      "CreatePlan": "Створити графік виплат",
      "EditPlan": "Змінити графік виплат"
    }
  },
  "page": {
    "state": {
      "Completed": "Виплачені",
      "Pending": "Актуальні"
    },
    "Title": "Кредити"
  },
  "pageItem": {
    "button": {
      "DeleteKeepTransaction": "Видалити, але зберегти транзакцію",
      "DeleteWithTransaction": "Видалити разом з транзакцією",
      "Finish": "Завершити",
      "PayNow": "Заплатити зараз",
      "UndoFinish": "Відмінити завершення"
    },
    "label": {
      "AlreadyPaidAmount": "Виплачено",
      "CreatePayCalendar": "Створити графік виплат",
      "NextPayment": "Наступний платіж",
      "ViewPayCalendar": "Переглянути графік виплат"
    },
    "message": {
      "ConfirmDelete": "Ви справді бажаєте видалити цю кредитну операцію? Це не вплине на залишки на рахунках.",
      "ConfirmDeleteMayKeepTransaction": "Ця кредитна операція пов'язана з транзакцією. Видаливши цю кредитну операцію, Ви можете як зберегти транзакцію, так і видалити її.",
      "ConfirmFinish": "Завершити кредит?",
      "ConfirmUndoFinish": "Відмінити завершення кредиту?",
      "DeleteConfirm": "Ви справді бажаєте видалити цей кредит?"
    },
    "title": {
      "DeleteCredit": "Видалення Кредиту",
      "Operations": "Історія операцій",
      "PaymentsChart": "Діаграма виплат"
    }
  }
}

=== cubux-net/web-v2-i18n/locales/el/front/credits.json
{
  "button": {
    "AddCredit": "Προσθήκη\nΠιστωτική"
  },
  "error": {
    "SomePlanChangedWasNotSaved": "Ορισμένες αλλαγές δεν ήταν δυνατό να αποθηκευτούν λόγω σφαλμάτων."
  },
  "form": {
    "hint": {
      "Duration": "Μήνες",
      "FeeFromSyncAccountsAll": "Οι αυτόματες πληρωμές δεν θα λειτουργούν για συγχρονισμένους λογαριασμούς.",
      "FeeFromSyncAccountsSome": "Οι αυτόματες πληρωμές δεν θα λειτουργούν για συγχρονισμένους λογαριασμούς."
    },
    "label": {
      "Duration": "Ορος",
      "EndDate": "ημερομηνία λήξης",
      "FeeFromAccounts": "Πληρώστε αυτόματα από λογαριασμούς",
      "Name": "Ονομα",
      "OnlyCurrency": "Μην πιστώσετε",
      "PlanType": "Τρόπος πληρωμής",
      "Rate": "Προσφορά",
      "ReceiveCreditToAccount": "Πίστωση σε λογαριασμό",
      "RemainToFee": "Μένει να πληρώσει",
      "StartDate": "ημερομηνία έναρξης",
      "TotalCreditAmount": "Ποσό που έχει εισπραχθεί",
      "TotalPayAmount": "Συνολικές πληρωμές"
    },
    "planType": {
      "Ann": "Πρόσοδος",
      "Diff": "Διαφοροποιημένο"
    },
    "title": {
      "CreateCredit": "Προσθέστε πίστωση",
      "EditCredit": "Αλλαγή δανείου"
    }
  },
  "formOperation": {
    "label": {
      "DealWithAccounts": "Επηρεάζει τα υπόλοιπα λογαριασμών",
      "LinkToPlan": "Κλείστε στο γράφημα",
      "LinkToPlanItem": "{date}: {paid} {ofTotal} ({percent}%)",
      "NoLinkToPlan": "εκτός σχεδίου",
      "SelectTransaction": "Επιλέξτε μια συναλλαγή...",
      "TransactionLinked": "Δεσμευμένη συναλλαγή για {amount} για {date}{ifAccountValid, select, 0{ σε άλλο λογαριασμό} other{}}",
      "TransactionNotLinked": "Η συναλλαγή δεν είναι δεσμευμένη"
    },
    "message": {
      "SelectTransaction": "Καθορίστε τη συναλλαγή.",
      "TransactionFetchFailed": "Αποτυχία λήψης λεπτομερειών για την επιλεγμένη συναλλαγή."
    }
  },
  "formPlan": {
    "label": {
      "PaidAmount": "Εξοφλήθηκε"
    },
    "title": {
      "CreatePlan": "Δημιουργήστε ένα ημερολόγιο πληρωμής",
      "EditPlan": "Αλλάξτε το ημερολόγιο πληρωμής"
    }
  },
  "page": {
    "state": {
      "Completed": "Εξοφλήθηκε",
      "Pending": "Τοπικός"
    },
    "Title": "Δάνεια"
  },
  "pageItem": {
    "button": {
      "DeleteKeepTransaction": "Διαγραφή αλλά διατήρηση της συναλλαγής",
      "DeleteWithTransaction": "Διαγραφή μαζί με τη συναλλαγή",
      "Finish": "Ολοκληρώθηκε",
      "PayNow": "Πλήρωσε τώρα",
      "UndoFinish": "Ακύρωση ολοκλήρωσης"
    },
    "label": {
      "AlreadyPaidAmount": "Εξοφλήθηκε",
      "CreatePayCalendar": "Δημιουργήστε ένα ημερολόγιο πληρωμής",
      "NextPayment": "Επόμενη πληρωμή",
      "ViewPayCalendar": "Προβολή ημερολογίου πληρωμής"
    },
    "message": {
      "ConfirmDelete": "Είστε βέβαιοι ότι θέλετε να διαγράψετε τη συναλλαγή πίστωσης; Τα υπόλοιπα λογαριασμών δεν θα επηρεαστούν.",
      "ConfirmDeleteMayKeepTransaction": "Αυτή η συναλλαγή πίστωσης σχετίζεται με μια συναλλαγή. Κατά τη διαγραφή αυτής της πιστωτικής λειτουργίας, μπορείτε είτε να αποχωρήσετε από τη συναλλαγή είτε να τη διαγράψετε.",
      "ConfirmFinish": "Ολοκληρώθηκε πίστωσης?",
      "ConfirmUndoFinish": "Ακύρωση ολοκλήρωσης πίστωσης?",
      "DeleteConfirm": "Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτό το δάνειο;"
    },
    "title": {
      "DeleteCredit": "Κατάργηση πίστωσης",
      "Operations": "Ιστορικό λειτουργιών",
      "PaymentsChart": "ΠΡΟΓΡΑΜΜΑ ΠΛΗΡΩΜΩΝ"
    }
  }
}

=== cubux-net/web-v2-i18n/locales/es/front/credits.json
{
  "button": {
    "AddCredit": "Agregar\nCrédito"
  },
  "error": {
    "SomePlanChangedWasNotSaved": "Algunos cambios no se guardaron debido a errores."
  },
  "form": {
    "hint": {
      "Duration": "Meses",
      "FeeFromSyncAccountsAll": "El pago automático no funcionará con cuentas sincronizadas.",
      "FeeFromSyncAccountsSome": "El pago automático no funcionará con cuentas sincronizadas."
    },
    "label": {
      "Duration": "Duración",
      "EndDate": "Fecha de finalización",
      "FeeFromAccounts": "Pagar automáticamente desde cuentas",
      "Name": "Nombre",
      "OnlyCurrency": "No agregar a la cuenta",
      "PlanType": "Tipo de plan",
      "Rate": "Tasa",
      "ReceiveCreditToAccount": "Recibir crédito a la cuenta",
      "RemainToFee": "Permanecer en la tarifa",
      "StartDate": "Fecha de inicio",
      "TotalCreditAmount": "Monto total del crédito",
      "TotalPayAmount": "Monto total del pago"
    },
    "planType": {
      "Ann": "Anualidad",
      "Diff": "Diferencial"
    },
    "title": {
      "CreateCredit": "Añadir crédito",
      "EditCredit": "Editar crédito"
    }
  },
  "formOperation": {
    "label": {
      "DealWithAccounts": "Afecta las cuentas",
      "LinkToPlan": "Enlace al plan",
      "LinkToPlanItem": "{date}: {paid} {ofTotal} ({percent}%)",
      "NoLinkToPlan": "fuera del plan",
      "SelectTransaction": "Seleccione transacción...",
      "TransactionLinked": "Transacción vinculada por {amount} en {date}{ifAccountValid, select, 0{ con otra cuenta} other{}}",
      "TransactionNotLinked": "Ninguna transacción vinculada"
    },
    "message": {
      "SelectTransaction": "Por favor, seleccione transacción.",
      "TransactionFetchFailed": "No se pudieron recuperar los detalles de la transacción vinculada."
    }
  },
  "formPlan": {
    "label": {
      "PaidAmount": "Pagado"
    },
    "title": {
      "CreatePlan": "Crear plan",
      "EditPlan": "Editar plan"
    }
  },
  "page": {
    "state": {
      "Completed": "Finalizado",
      "Pending": "Actual"
    },
    "Title": "Créditos"
  },
  "pageItem": {
    "button": {
      "DeleteKeepTransaction": "Eliminar operación, mantener transacciones",
      "DeleteWithTransaction": "Eliminar CON transacción",
      "Finish": "Completo",
      "PayNow": "Paga ahora",
      "UndoFinish": "Cancelar finalización"
    },
    "label": {
      "AlreadyPaidAmount": "ya pagado",
      "CreatePayCalendar": "Crear plan de pagos",
      "NextPayment": "Próximo pago",
      "ViewPayCalendar": "Ver plan de pagos"
    },
    "message": {
      "ConfirmDelete": "¿Está seguro de eliminar esta operación de crédito? Esta acción no cambiará el saldo de las cuentas.",
      "ConfirmDeleteMayKeepTransaction": "Esta operación de crédito está vinculada a la transacción. Puede conservar la transacción o eliminarla también mientras elimina la operación de crédito.",
      "ConfirmFinish": "¿Crédito completo?",
      "ConfirmUndoFinish": "¿Cancelar la finalización del crédito?",
      "DeleteConfirm": "¿Estás seguro de eliminar este crédito por completo?"
    },
    "title": {
      "DeleteCredit": "Eliminar crédito",
      "Operations": "Historial de operaciones",
      "PaymentsChart": "Tabla de pagos"
    }
  }
}
