=== cubux-net/web-v2-i18n/schemas/front/plan.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "string": {
      "type": "string",
      "minLength": 1
    }
  },
  "type": "object",
  "properties": {
    "label": {
      "type": "object",
      "properties": {
        "item": {
          "type": "object",
          "properties": {
            "NextDate": {
              "$ref": "#/$defs/string"
            },
            "Repeat": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["NextDate", "Repeat"]
        },
        "stats": {
          "type": "object",
          "properties": {
            "PlannedTurnoverUntil": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["PlannedTurnoverUntil"]
        }
      },
      "required": ["item", "stats"]
    },
    "message": {
      "type": "object",
      "properties": {
        "ConfirmDelete": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["ConfirmDelete"]
    },
    "page": {
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["title"]
    },
    "when": {
      "type": "object",
      "properties": {
        "quarter": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["quarter"]
    }
  },
  "required": ["label", "message", "page", "when"]
}

=== cubux-net/web-v2-i18n/locales/el/front/plan.json
{
  "label": {
    "item": {
      "NextDate": "Επόμενη ημερομηνία",
      "Repeat": "Επαναλαμβάνω"
    },
    "stats": {
      "PlannedTurnoverUntil": "Προγραμματισμένες εργασίες πριν {date}"
    }
  },
  "message": {
    "ConfirmDelete": "Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτήν την προγραμματισμένη συναλλαγή;"
  },
  "page": {
    "title": "Προγραμματισμένες Συναλλαγές"
  },
  "when": {
    "quarter": "{date}-ος {quartMonth, select, 1{1. μήνας} 2{2. μήνας} 3{3. μήνας} other{}}"
  }
}

=== cubux-net/web-v2-i18n/locales/en/front/plan.json
{
  "label": {
    "item": {
      "NextDate": "Next date",
      "Repeat": "Repeat"
    },
    "stats": {
      "PlannedTurnoverUntil": "Planned operations until {date}"
    }
  },
  "message": {
    "ConfirmDelete": "Are you sure to delete this planned operation?"
  },
  "page": {
    "title": "Planned Transactions"
  },
  "when": {
    "quarter": "{date} of {quartMonth, select, 1{1st month} 2{2nd month} 3{3rd month} other{}}"
  }
}

=== cubux-net/web-v2-i18n/locales/ru/front/plan.json
{
  "label": {
    "item": {
      "NextDate": "След. дата",
      "Repeat": "Повтор"
    },
    "stats": {
      "PlannedTurnoverUntil": "Запланированные операции до {date}"
    }
  },
  "message": {
    "ConfirmDelete": "Вы уверены, что хотите удалить эту плановую транзакцию?"
  },
  "page": {
    "title": "Плановые транзакции"
  },
  "when": {
    "quarter": "{date}-го {quartMonth, select, 1{в 1-й месяц} 2{во 2-й месяц} 3{в 3-й месяц} other{}}"
  }
}

=== cubux-net/web-v2-i18n/locales/cs/front/plan.json
{
  "label": {
    "item": {
      "NextDate": "Příští datum",
      "Repeat": "Opakovat"
    },
    "stats": {
      "PlannedTurnoverUntil": "Plánované operace {date}"
    }
  },
  "message": {
    "ConfirmDelete": "Opravdu chcete tuto naplánovanou transakci smazat?"
  },
  "page": {
    "title": "Plánované transakce"
  },
  "when": {
    "quarter": "{date}-ého {quartMonth, select, 1{1. měsic} 2{2. měsic} 3{3. měsic} other{}}"
  }
}

=== cubux-net/web-v2-i18n/locales/es/front/plan.json
{
  "label": {
    "item": {
      "NextDate": "próxima fecha",
      "Repeat": "Repetir"
    },
    "stats": {
      "PlannedTurnoverUntil": "Operaciones planificadas hasta {date}"
    }
  },
  "message": {
    "ConfirmDelete": "¿Está seguro de eliminar esta operación planificada?"
  },
  "page": {
    "title": "Transacciones planificadas"
  },
  "when": {
    "quarter": "{date} de {quartMonth, select, 1{1er. mes} 2{2do. mes} 3{3er. mes} other{}}"
  }
}
