=== cubux-net/web-v2-i18n/schemas/front/receipts.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "string": {
      "type": "string",
      "minLength": 1
    }
  },
  "type": "object",
  "properties": {
    "assignTransaction": {
      "type": "object",
      "properties": {
        "message": {
          "type": "object",
          "properties": {
            "AddGroupHelp": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["AddGroupHelp"]
        }
      },
      "required": ["message"]
    },
    "button": {
      "type": "object",
      "properties": {
        "AssignCategories": {
          "$ref": "#/$defs/string"
        },
        "CreateReceiptAndLeave": {
          "$ref": "#/$defs/string"
        },
        "InputReceiptManually": {
          "$ref": "#/$defs/string"
        },
        "InputReceiptManuallyByPositions": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "AssignCategories",
        "CreateReceiptAndLeave",
        "InputReceiptManually",
        "InputReceiptManuallyByPositions"
      ]
    },
    "fetchState": {
      "type": "object",
      "properties": {
        "Fetching": {
          "$ref": "#/$defs/string"
        },
        "Fulfilled": {
          "$ref": "#/$defs/string"
        },
        "Invalid": {
          "$ref": "#/$defs/string"
        },
        "Rejected": {
          "$ref": "#/$defs/string"
        },
        "Validation": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["Fetching", "Fulfilled", "Invalid", "Rejected", "Validation"]
    },
    "label": {
      "type": "object",
      "properties": {
        "Date": {
          "$ref": "#/$defs/string"
        },
        "FetchAttempts": {
          "$ref": "#/$defs/string"
        },
        "FetchState": {
          "$ref": "#/$defs/string"
        },
        "LastFetchAt": {
          "$ref": "#/$defs/string"
        },
        "NextFetchAfter": {
          "$ref": "#/$defs/string"
        },
        "Shop": {
          "$ref": "#/$defs/string"
        },
        "Sum": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "Date",
        "FetchAttempts",
        "FetchState",
        "LastFetchAt",
        "NextFetchAfter",
        "Shop",
        "Sum"
      ]
    },
    "manual": {
      "type": "object",
      "properties": {
        "message": {
          "type": "object",
          "properties": {
            "CreateUnfinishedReceiptAndLeave": {
              "$ref": "#/$defs/string"
            },
            "ReceiptDataReadyCheckAndSave": {
              "$ref": "#/$defs/string"
            },
            "ReceiptIsInvalidOfMissing": {
              "$ref": "#/$defs/string"
            },
            "StayHereAndWait": {
              "$ref": "#/$defs/string"
            },
            "WaitingReceiptDataThisMayBeLong": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "CreateUnfinishedReceiptAndLeave",
            "ReceiptDataReadyCheckAndSave",
            "ReceiptIsInvalidOfMissing",
            "StayHereAndWait",
            "WaitingReceiptDataThisMayBeLong"
          ]
        }
      },
      "required": ["message"]
    },
    "statsPage": {
      "type": "object",
      "properties": {
        "Title": {
          "$ref": "#/$defs/string"
        },
        "button": {
          "type": "object",
          "properties": {
            "MoreReceipts": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["MoreReceipts"]
        },
        "label": {
          "type": "object",
          "properties": {
            "PositionPriceVary": {
              "$ref": "#/$defs/string"
            },
            "Shopping": {
              "$ref": "#/$defs/string"
            },
            "byCategories": {
              "$ref": "#/$defs/string"
            },
            "byPositions": {
              "$ref": "#/$defs/string"
            },
            "byShops": {
              "$ref": "#/$defs/string"
            },
            "mostCheapPrice": {
              "$ref": "#/$defs/string"
            },
            "mostExpensivePrice": {
              "$ref": "#/$defs/string"
            },
            "priceDifference": {
              "$ref": "#/$defs/string"
            },
            "unknownShop": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "PositionPriceVary",
            "Shopping",
            "byCategories",
            "byPositions",
            "byShops",
            "mostCheapPrice",
            "mostExpensivePrice",
            "priceDifference",
            "unknownShop"
          ]
        },
        "message": {
          "type": "object",
          "properties": {
            "ConfirmDeleteReceipt": {
              "$ref": "#/$defs/string"
            },
            "NoPositions": {
              "$ref": "#/$defs/string"
            },
            "SelectPositionsToTrack": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "ConfirmDeleteReceipt",
            "NoPositions",
            "SelectPositionsToTrack"
          ]
        }
      },
      "required": ["Title", "button", "label", "message"]
    }
  },
  "required": [
    "assignTransaction",
    "button",
    "fetchState",
    "label",
    "manual",
    "statsPage"
  ]
}

=== cubux-net/web-v2-i18n/locales/el/front/receipts.json
{
  "assignTransaction": {
    "message": {
      "AddGroupHelp": "Επιλέξτε τον λογαριασμό και την κατηγορία, σημειώστε τα απαιτούμενα στοιχεία και κάντε κλικ στο [Προσθήκη]. Τα επιλεγμένα στοιχεία θα ομαδοποιηθούν σε μία συναλλαγή."
    }
  },
  "button": {
    "AssignCategories": "Αντιστοίχιση κατηγοριών",
    "CreateReceiptAndLeave": "Δημιουργήστε μια επιταγή και φύγετε",
    "InputReceiptManually": "Χειροκίνητη εισαγωγή επιταγής",
    "InputReceiptManuallyByPositions": "Χειροκίνητη εισαγωγή μιας επιταγής με το όνομα"
  },
  "fetchState": {
    "Fetching": "Αναμονή για δεδομένα",
    "Fulfilled": "Ελήφθη",
    "Invalid": "Ανακριβής",
    "Rejected": "Απορρίφθηκε",
    "Validation": "Επαλήθευση σε εκκρεμότητα"
  },
  "label": {
    "Date": "ημερομηνία",
    "FetchAttempts": "Ολοκληρώθηκαν οι προσπάθειες",
    "FetchState": "Κατάσταση ουράς",
    "LastFetchAt": "Η τελευταία προσπάθεια ήταν",
    "NextFetchAfter": "Επόμενη προσπάθεια μετά",
    "Shop": "Κατάστημα",
    "Sum": "Αθροισμα"
  },
  "manual": {
    "message": {
      "CreateUnfinishedReceiptAndLeave": "Μπορείτε να δημιουργήσετε μια ημιτελή επιταγή αυτή τη στιγμή και να φύγετε. Ο έλεγχος θα υποβληθεί σε επεξεργασία όταν έρθει η σειρά.",
      "ReceiptDataReadyCheckAndSave": "Τα δεδομένα παραλαβής ελήφθησαν με επιτυχία.",
      "ReceiptIsInvalidOfMissing": "Δεν είναι δυνατή η λήψη δεδομένων ελέγχου. Ο έλεγχος είτε δεν είναι σωστός είτε τα δεδομένα δεν βρέθηκαν.",
      "StayHereAndWait": "Μπορείτε να περιμένετε για το αποτέλεσμα και μόνο τότε να δημιουργήσετε μια απόδειξη.",
      "WaitingReceiptDataThisMayBeLong": "Η επιταγή βρίσκεται στην ουρά για επεξεργασία. Αυτό μπορεί να διαρκέσει πολύ, ανάλογα με τη συμφόρηση της ουράς."
    }
  },
  "statsPage": {
    "button": {
      "MoreReceipts": "Περισσότεροι έλεγχοι"
    },
    "label": {
      "byCategories": "Ανά κατηγορία",
      "byPositions": "Με αγαθά",
      "byShops": "Ψώνια",
      "mostCheapPrice": "Χαμηλότερο",
      "mostExpensivePrice": "Το ψηλότερο",
      "PositionPriceVary": "Αλλαγή τιμής προϊόντος",
      "priceDifference": "Διαφορά",
      "Shopping": "Ψώνια",
      "unknownShop": "άγνωστο κατάστημα"
    },
    "message": {
      "ConfirmDeleteReceipt": "Είστε βέβαιοι ότι θέλετε να διαγράψετε επιταγής?",
      "NoPositions": "Χωρίς θέσεις",
      "SelectPositionsToTrack": "Παρακαλώ επιλέξτε {maxCount, plural, =1{θέση} one{πριν # θέσεις} few{πριν # θέσεις} other{πριν # θέσεις}} για να δείτε τις τιμές."
    },
    "Title": "Στατιστικά στοιχεία αγορών"
  }
}

=== cubux-net/web-v2-i18n/locales/en/front/receipts.json
{
  "assignTransaction": {
    "message": {
      "AddGroupHelp": "Select the Account and Category, mark the required items and click [Add]. The selected items will be grouped into one transaction."
    }
  },
  "button": {
    "AssignCategories": "Assign categories",
    "CreateReceiptAndLeave": "Create receipt and leave",
    "InputReceiptManually": "Input receipt manually",
    "InputReceiptManuallyByPositions": "Input receipt manually by positions"
  },
  "fetchState": {
    "Fetching": "Waiting for data",
    "Fulfilled": "Fulfilled",
    "Invalid": "Invalid",
    "Rejected": "Rejected",
    "Validation": "Waiting for validation"
  },
  "label": {
    "Date": "Date",
    "FetchAttempts": "Attempts performed",
    "FetchState": "Status in queue",
    "LastFetchAt": "Last attempt was at",
    "NextFetchAfter": "Next attempt after",
    "Shop": "Shop",
    "Sum": "Sum"
  },
  "manual": {
    "message": {
      "CreateUnfinishedReceiptAndLeave": "You can create unfinished receipt right now. The receipt will be processed with respect to queue.",
      "ReceiptDataReadyCheckAndSave": "Receipt data fulfilled successfully.",
      "ReceiptIsInvalidOfMissing": "Unable to get data for the receipt. Either receipt in invalid, or data was not found.",
      "StayHereAndWait": "You can stay here and wait for the result. After then you would save the receipt.",
      "WaitingReceiptDataThisMayBeLong": "The receipt is in queue. This may take long time depending on queue load."
    }
  },
  "statsPage": {
    "button": {
      "MoreReceipts": "More receipts"
    },
    "label": {
      "byCategories": "By categories",
      "byPositions": "By positions",
      "byShops": "By shops",
      "mostCheapPrice": "Cheapest",
      "mostExpensivePrice": "Most expensive",
      "PositionPriceVary": "Position price varying",
      "priceDifference": "Difference",
      "Shopping": "Shopping",
      "unknownShop": "unknown shop"
    },
    "message": {
      "ConfirmDeleteReceipt": "Are you sure to delete this receipt?",
      "NoPositions": "No positions",
      "SelectPositionsToTrack": "Select {maxCount, plural, =1{a position} one{up to # position} other{up to # positions}} to view prices."
    },
    "Title": "Shopping statistic"
  }
}
