=== cubux-net/web-v2-i18n/schemas/front/targets.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "string": {
      "type": "string",
      "minLength": 1
    }
  },
  "type": "object",
  "properties": {
    "RemoveQuest": {
      "$ref": "#/$defs/string"
    },
    "button": {
      "type": "object",
      "properties": {
        "AddTarget": {
          "$ref": "#/$defs/string"
        },
        "Complete": {
          "$ref": "#/$defs/string"
        },
        "PayManual": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "AddTarget",
        "Complete",
        "PayManual"
      ]
    },
    "label": {
      "type": "object",
      "properties": {
        "Amount": {
          "$ref": "#/$defs/string"
        },
        "CreateNewAccount": {
          "$ref": "#/$defs/string"
        },
        "HowToAccumulate": {
          "$ref": "#/$defs/string"
        },
        "Interval": {
          "$ref": "#/$defs/string"
        },
        "Name": {
          "$ref": "#/$defs/string"
        },
        "NewAccountName": {
          "$ref": "#/$defs/string"
        },
        "PayAmount": {
          "$ref": "#/$defs/string"
        },
        "PayFromAccount": {
          "$ref": "#/$defs/string"
        },
        "Remain": {
          "$ref": "#/$defs/string"
        },
        "ReserveOnAccount": {
          "$ref": "#/$defs/string"
        },
        "StartPaySince": {
          "$ref": "#/$defs/string"
        },
        "TotalAmount": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "Amount",
        "CreateNewAccount",
        "HowToAccumulate",
        "Interval",
        "Name",
        "NewAccountName",
        "PayAmount",
        "PayFromAccount",
        "Remain",
        "ReserveOnAccount",
        "StartPaySince",
        "TotalAmount"
      ]
    },
    "state": {
      "type": "object",
      "properties": {
        "Completed": {
          "$ref": "#/$defs/string"
        },
        "Pending": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "Completed",
        "Pending"
      ]
    },
    "title": {
      "type": "object",
      "properties": {
        "CreateTarget": {
          "$ref": "#/$defs/string"
        },
        "OperationsHistory": {
          "$ref": "#/$defs/string"
        },
        "PayManual": {
          "$ref": "#/$defs/string"
        },
        "page": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "CreateTarget",
        "OperationsHistory",
        "PayManual",
        "page"
      ]
    }
  },
  "required": [
    "RemoveQuest",
    "button",
    "label",
    "state",
    "title"
  ]
}

=== cubux-net/web-v2-i18n/locales/en/front/targets.json
{
  "button": {
    "AddTarget": "Add\ntarget",
    "Complete": "Complete",
    "PayManual": "Pay manual"
  },
  "label": {
    "Amount": "Amount",
    "CreateNewAccount": "Create new account",
    "HowToAccumulate": "How to accumulate?",
    "Interval": "Interval",
    "Name": "Name",
    "NewAccountName": "New account name",
    "PayAmount": "Pay amount",
    "PayFromAccount": "Pay from account",
    "Remain": "Remain",
    "ReserveOnAccount": "Reserve on source account",
    "StartPaySince": "Start pay since",
    "TotalAmount": "Total amount"
  },
  "RemoveQuest": "Are you sure to delete the Goal with all related transactions? It may change accounts balance.",
  "state": {
    "Completed": "Completed",
    "Pending": "Pending"
  },
  "title": {
    "CreateTarget": "Create target",
    "OperationsHistory": "Operations history",
    "page": "Targets",
    "PayManual": "Pay manual"
  }
}
