=== cubux-net/web-v2-i18n/schemas/front/transactions.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "string": {
      "type": "string",
      "minLength": 1
    }
  },
  "type": "object",
  "properties": {
    "message": {
      "type": "object",
      "properties": {
        "ConfirmDeleteTransaction": {
          "$ref": "#/$defs/string"
        },
        "ConfirmPlannedTransaction": {
          "$ref": "#/$defs/string"
        },
        "ConfirmSplitTransaction": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "ConfirmDeleteTransaction",
        "ConfirmPlannedTransaction",
        "ConfirmSplitTransaction"
      ]
    },
    "multiDelete": {
      "type": "object",
      "properties": {
        "confirm": {
          "type": "object",
          "properties": {
            "Content": {
              "$ref": "#/$defs/string"
            },
            "OK": {
              "$ref": "#/$defs/string"
            },
            "Title": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Content", "OK", "Title"]
        }
      },
      "required": ["confirm"]
    },
    "page": {
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["title"]
    },
    "table": {
      "type": "object",
      "properties": {
        "button": {
          "type": "object",
          "properties": {
            "ConfigureTable": {
              "$ref": "#/$defs/string"
            },
            "CreateCopy": {
              "$ref": "#/$defs/string"
            },
            "MoreTransactions": {
              "$ref": "#/$defs/string"
            },
            "ShowReceipt": {
              "$ref": "#/$defs/string"
            },
            "SplitTransfer": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "ConfigureTable",
            "CreateCopy",
            "MoreTransactions",
            "ShowReceipt",
            "SplitTransfer"
          ]
        },
        "content": {
          "type": "object",
          "properties": {
            "NothingWasFound": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["NothingWasFound"]
        },
        "filter": {
          "type": "object",
          "properties": {
            "account": {
              "type": "object",
              "properties": {
                "label": {
                  "type": "object",
                  "properties": {
                    "SelectAccount": {
                      "$ref": "#/$defs/string"
                    }
                  },
                  "required": ["SelectAccount"]
                }
              },
              "required": ["label"]
            },
            "amount": {
              "type": "object",
              "properties": {
                "label": {
                  "type": "object",
                  "properties": {
                    "Amount": {
                      "$ref": "#/$defs/string"
                    }
                  },
                  "required": ["Amount"]
                }
              },
              "required": ["label"]
            },
            "category": {
              "type": "object",
              "properties": {
                "label": {
                  "type": "object",
                  "properties": {
                    "SelectCategory": {
                      "$ref": "#/$defs/string"
                    }
                  },
                  "required": ["SelectCategory"]
                }
              },
              "required": ["label"]
            },
            "project": {
              "type": "object",
              "properties": {
                "label": {
                  "type": "object",
                  "properties": {
                    "SelectProject": {
                      "$ref": "#/$defs/string"
                    }
                  },
                  "required": ["SelectProject"]
                }
              },
              "required": ["label"]
            },
            "type": {
              "type": "object",
              "properties": {
                "label": {
                  "type": "object",
                  "properties": {
                    "Expenses": {
                      "$ref": "#/$defs/string"
                    },
                    "Incomes": {
                      "$ref": "#/$defs/string"
                    },
                    "Loans": {
                      "$ref": "#/$defs/string"
                    },
                    "Transfers": {
                      "$ref": "#/$defs/string"
                    }
                  },
                  "required": ["Expenses", "Incomes", "Loans", "Transfers"]
                }
              },
              "required": ["label"]
            },
            "user": {
              "type": "object",
              "properties": {
                "label": {
                  "type": "object",
                  "properties": {
                    "SelectUser": {
                      "$ref": "#/$defs/string"
                    },
                    "deleted": {
                      "$ref": "#/$defs/string"
                    },
                    "notInTeam": {
                      "$ref": "#/$defs/string"
                    }
                  },
                  "required": ["SelectUser", "deleted", "notInTeam"]
                }
              },
              "required": ["label"]
            }
          },
          "required": [
            "account",
            "amount",
            "category",
            "project",
            "type",
            "user"
          ]
        },
        "head": {
          "type": "object",
          "properties": {
            "config": {
              "type": "object",
              "properties": {
                "DisplayAdaptive": {
                  "$ref": "#/$defs/string"
                },
                "DisplayAlways": {
                  "$ref": "#/$defs/string"
                },
                "DisplayExtraColumns": {
                  "$ref": "#/$defs/string"
                },
                "DisplayNever": {
                  "$ref": "#/$defs/string"
                },
                "Title": {
                  "$ref": "#/$defs/string"
                }
              },
              "required": [
                "DisplayAdaptive",
                "DisplayAlways",
                "DisplayExtraColumns",
                "DisplayNever",
                "Title"
              ]
            },
            "label": {
              "type": "object",
              "properties": {
                "CategoryDescription": {
                  "$ref": "#/$defs/string"
                },
                "Remain": {
                  "$ref": "#/$defs/string"
                }
              },
              "required": ["CategoryDescription", "Remain"]
            }
          },
          "required": ["config", "label"]
        }
      },
      "required": ["button", "content", "filter", "head"]
    },
    "transferJoin": {
      "type": "object",
      "properties": {
        "button": {
          "type": "object",
          "properties": {
            "Join": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Join"]
        },
        "message": {
          "type": "object",
          "properties": {
            "ChooseCommissionCategory": {
              "$ref": "#/$defs/string"
            },
            "ThisCanBeDoneWithCommission": {
              "$ref": "#/$defs/string"
            },
            "YouAreGoingToJoinWhat": {
              "$ref": "#/$defs/string"
            }
          },
          "required": [
            "ChooseCommissionCategory",
            "ThisCanBeDoneWithCommission",
            "YouAreGoingToJoinWhat"
          ]
        }
      },
      "required": ["button", "message"]
    },
    "unconfirmed": {
      "type": "object",
      "properties": {
        "EndTitle": {
          "$ref": "#/$defs/string"
        },
        "Title": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["EndTitle", "Title"]
    }
  },
  "required": [
    "message",
    "multiDelete",
    "page",
    "table",
    "transferJoin",
    "unconfirmed"
  ]
}

=== cubux-net/web-v2-i18n/locales/el/front/transactions.json
{
  "message": {
    "ConfirmDeleteTransaction": "Είστε βέβαιοι ότι θέλετε να διαγράψετε τη συναλλαγή; Δεν είναι δυνατή η αναίρεση αυτής της ενέργειας.",
    "ConfirmPlannedTransaction": "Είστε βέβαιοι να επιβεβαιώσετε τη συναλλαγή;",
    "ConfirmSplitTransaction": "Είστε βέβαιοι ότι θέλετε να διαιρέσετε αυτήν τη μεταφορά?"
  },
  "multiDelete": {
    "confirm": {
      "Content": "Είστε βέβαιοι ότι θέλετε να διαγράψετε <1>{n, plural, one{# transaction} other{# transactions}}</1>? Δεν είναι δυνατή η αναίρεση αυτής της ενέργειας.",
      "OK": "Διαγραφή {n, plural, one{# transaction} other{# transactions}}",
      "Title": "Διαγραφή επιλεγμένων συναλλαγών"
    }
  },
  "page": {
    "title": "Συναλλαγές"
  },
  "table": {
    "button": {
      "ConfigureTable": "Ρύθμιση πίνακα",
      "CreateCopy": "Δημιουργία αντιγράφου",
      "MoreTransactions": "Περισσότερες συναλλαγές",
      "ShowReceipt": "Εμφάνιση απόδειξης",
      "SplitTransfer": "Διαίρεση μεταφοράς"
    },
    "content": {
      "NothingWasFound": "Δεν υπάρχουν συναλλαγές"
    },
    "filter": {
      "account": {
        "label": {
          "SelectAccount": "Επιλογή λογαριασμού"
        }
      },
      "amount": {
        "label": {
          "Amount": "Καταχωρίστε ένα ποσό"
        }
      },
      "category": {
        "label": {
          "SelectCategory": "Επιλογή κατηγορίας"
        }
      },
      "project": {
        "label": {
          "SelectProject": "Επιλογή έργου"
        }
      },
      "type": {
        "label": {
          "Expenses": "Έξοδα",
          "Incomes": "Εισοδήματα",
          "Loans": "Δάνεια",
          "Transfers": "Μεταφορές"
        }
      },
      "user": {
        "label": {
          "deleted": "διαγράφηκε",
          "notInTeam": "δεν ανήκει στην ομάδα",
          "SelectUser": "Επιλογή χρήστη"
        }
      }
    },
    "head": {
      "config": {
        "DisplayAdaptive": "Προσαρμοστική",
        "DisplayAlways": "Πάντα",
        "DisplayExtraColumns": "Επιλογή συνθηκών για εμφάνιση επιπλέον στηλών.",
        "DisplayNever": "Ποτέ",
        "Title": "Ρύθμιση παραμέτρων πίνακα"
      },
      "label": {
        "CategoryDescription": "Κατηγορία, περιγραφή",
        "Remain": "Παραμένουν"
      }
    }
  },
  "transferJoin": {
    "button": {
      "Join": "Σύνδεση για μεταφορά"
    },
    "message": {
      "ChooseCommissionCategory": "Επιλέξτε μια κατηγορία για συναλλαγή με προμήθεια:",
      "ThisCanBeDoneWithCommission": "Αυτό μπορεί να γίνει με τη δημιουργία μιας συναλλαγής προμήθειας για <1>{sum}</1>.",
      "YouAreGoingToJoinWhat": "Σας ζητείται να συμμετάσχετε σε μια μεταφορά δύο συναλλαγών με διαφορετικά ποσά:"
    }
  },
  "unconfirmed": {
    "EndTitle": "Τακτικές συναλλαγές",
    "Title": "Μη επιβεβαιωμένες συναλλαγές"
  }
}

=== cubux-net/web-v2-i18n/locales/ru/front/transactions.json
{
  "message": {
    "ConfirmDeleteTransaction": "Вы уверены, что хотите удалить транзакцию? Операцию нельзя будет отменить.",
    "ConfirmPlannedTransaction": "Вы уверены, что хотите подтвердить транзакцию?",
    "ConfirmSplitTransaction": "Вы уверены, что хотите разделить этот перевод?"
  },
  "multiDelete": {
    "confirm": {
      "Content": "Вы уверены, что хотите удалить <1>{n, plural, one{# транзакцию} few{# транзакции} other{# транзакций}}</1>? Операцию нельзя будет отменить.",
      "OK": "Удалить {n, plural, one{# транзакцию} few{# транзакции} other{# транзакций}}",
      "Title": "Удаление отмеченных транзакций"
    }
  },
  "page": {
    "title": "Транзакции"
  },
  "table": {
    "button": {
      "ConfigureTable": "Настроить таблицу",
      "CreateCopy": "Создать копию",
      "MoreTransactions": "Ещё транзакции",
      "ShowReceipt": "Показать чек",
      "SplitTransfer": "Разделить перевод"
    },
    "content": {
      "NothingWasFound": "Нет транзакций"
    },
    "filter": {
      "account": {
        "label": {
          "SelectAccount": "Выберите счёт"
        }
      },
      "amount": {
        "label": {
          "Amount": "Укажите сумму"
        }
      },
      "category": {
        "label": {
          "SelectCategory": "Выберите категорию"
        }
      },
      "project": {
        "label": {
          "SelectProject": "Выберите проект"
        }
      },
      "type": {
        "label": {
          "Expenses": "Расходы",
          "Incomes": "Доходы",
          "Loans": "Долги",
          "Transfers": "Переводы"
        }
      },
      "user": {
        "label": {
          "deleted": "удалён",
          "notInTeam": "не в команде",
          "SelectUser": "Выберите пользователя"
        }
      }
    },
    "head": {
      "config": {
        "DisplayAdaptive": "Адаптивно",
        "DisplayAlways": "Всегда",
        "DisplayExtraColumns": "Выберите условия для вывода дополнительных столбцов.",
        "DisplayNever": "Никогда",
        "Title": "Настройка таблицы"
      },
      "label": {
        "CategoryDescription": "Категория, Описание",
        "Remain": "Остаток"
      }
    }
  },
  "transferJoin": {
    "button": {
      "Join": "Объединить в перевод"
    },
    "message": {
      "ChooseCommissionCategory": "Пожалуйста, укажите категорию для создания расхода комиссии:",
      "ThisCanBeDoneWithCommission": "Это может быть выполнено, если создать расходную транзакцию комиссии на сумму <1>{sum}</1>.",
      "YouAreGoingToJoinWhat": "Вы хотите объединить в перевод транзакции с разными суммами:"
    }
  },
  "unconfirmed": {
    "EndTitle": "Обычные транзакции",
    "Title": "Неподтверждённые транзакции"
  }
}

=== cubux-net/web-v2-i18n/locales/en/front/transactions.json
{
  "message": {
    "ConfirmDeleteTransaction": "Are you sure to delete the transaction? This action cannot be undone.",
    "ConfirmPlannedTransaction": "Are you sure to confirm the transaction?",
    "ConfirmSplitTransaction": "Are you sure to split this transfer?"
  },
  "multiDelete": {
    "confirm": {
      "Content": "Are you sure to delete <1>{n, plural, one{# transaction} other{# transactions}}</1>? This action cannot be undone.",
      "OK": "Delete {n, plural, one{# transaction} other{# transactions}}",
      "Title": "Delete checked transactions"
    }
  },
  "page": {
    "title": "Transactions"
  },
  "table": {
    "button": {
      "ConfigureTable": "Configure table",
      "CreateCopy": "Create a copy",
      "MoreTransactions": "More transactions",
      "ShowReceipt": "Show receipt",
      "SplitTransfer": "Split transfer"
    },
    "content": {
      "NothingWasFound": "There are no transactions"
    },
    "filter": {
      "account": {
        "label": {
          "SelectAccount": "Select an account"
        }
      },
      "amount": {
        "label": {
          "Amount": "Provide an amount"
        }
      },
      "category": {
        "label": {
          "SelectCategory": "Select a category"
        }
      },
      "project": {
        "label": {
          "SelectProject": "Select a project"
        }
      },
      "type": {
        "label": {
          "Expenses": "Expenses",
          "Incomes": "Incomes",
          "Loans": "Loans",
          "Transfers": "Transfers"
        }
      },
      "user": {
        "label": {
          "deleted": "deleted",
          "notInTeam": "not in team",
          "SelectUser": "Select an user"
        }
      }
    },
    "head": {
      "config": {
        "DisplayAdaptive": "Adaptive",
        "DisplayAlways": "Always",
        "DisplayExtraColumns": "Choose conditions to display extra columns.",
        "DisplayNever": "Never",
        "Title": "Table configuration"
      },
      "label": {
        "CategoryDescription": "Category, Description",
        "Remain": "Remain"
      }
    }
  },
  "transferJoin": {
    "button": {
      "Join": "Join to transfer"
    },
    "message": {
      "ChooseCommissionCategory": "Please, choose a category for commission fee transaction:",
      "ThisCanBeDoneWithCommission": "This can be done by creating a commission fee transaction for <1>{sum}</1>.",
      "YouAreGoingToJoinWhat": "You are requested to join into a transfer two transactions with different amounts:"
    }
  },
  "unconfirmed": {
    "EndTitle": "Regular transactions",
    "Title": "Unconfirmed transactions"
  }
}

=== cubux-net/web-v2-i18n/locales/es/front/transactions.json
{
  "message": {
    "ConfirmDeleteTransaction": "¿Está seguro de eliminar la transacción? ",
    "ConfirmPlannedTransaction": "¿Está seguro de confirmar la transacción?",
    "ConfirmSplitTransaction": "¿Está seguro de dividir esta transferencia?"
  },
  "multiDelete": {
    "confirm": {
      "Content": "Está seguro de borrar <1>{n, plural, one{# transaction} other{# transactions}}</1>? Esta acción no se puede deshacer.",
      "OK": "Eliminar {n, plural, one{# transaction} other{# transactions}}",
      "Title": "Eliminar transacciones marcadas"
    }
  },
  "page": {
    "title": "Transacciones"
  },
  "table": {
    "button": {
      "ConfigureTable": "Configurar tabla",
      "CreateCopy": "crear una copia",
      "MoreTransactions": "Más transacciones",
      "ShowReceipt": "Mostrar recibo",
      "SplitTransfer": "Transferencia dividida"
    },
    "content": {
      "NothingWasFound": "No hay transacciones"
    },
    "filter": {
      "account": {
        "label": {
          "SelectAccount": "Seleccione una cuenta"
        }
      },
      "amount": {
        "label": {
          "Amount": "proporcione una cantidad"
        }
      },
      "category": {
        "label": {
          "SelectCategory": "Seleccione una categoría"
        }
      },
      "project": {
        "label": {
          "SelectProject": "Seleccione un proyecto"
        }
      },
      "type": {
        "label": {
          "Expenses": "Gastos",
          "Incomes": "Ingresos",
          "Loans": "Préstamos",
          "Transfers": "Transferencias"
        }
      },
      "user": {
        "label": {
          "deleted": "eliminado",
          "notInTeam": "no en equipo",
          "SelectUser": "Seleccione un usuario"
        }
      }
    },
    "head": {
      "config": {
        "DisplayAdaptive": "Adaptado",
        "DisplayAlways": "Siempre",
        "DisplayExtraColumns": "Elija condiciones para mostrar columnas adicionales.",
        "DisplayNever": "Nunca",
        "Title": "Configuración del gráfico"
      },
      "label": {
        "CategoryDescription": "Categoría, Descripción",
        "Remain": "Permanecer"
      }
    }
  },
  "transferJoin": {
    "button": {
      "Join": "Unirse para transferir"
    },
    "message": {
      "ChooseCommissionCategory": "Por favor, elija una categoría para la comisión de transacción:",
      "ThisCanBeDoneWithCommission": "Esto se puede hacer creando una transacción de tarifa de comisión para <1>{sum}</1>.",
      "YouAreGoingToJoinWhat": "Se le solicita unir en una transferencia dos transacciones con montos diferentes:"
    }
  },
  "unconfirmed": {
    "EndTitle": "Transacciones regulares",
    "Title": "Transacciones no confirmadas"
  }
}

=== cubux-net/web-v2-i18n/locales/cs/front/transactions.json
{
  "message": {
    "ConfirmDeleteTransaction": "Určitě chcete transakci odstranit? Operace nelze stornovat",
    "ConfirmPlannedTransaction": "Určitě chcete transakci potvrdit?",
    "ConfirmSplitTransaction": "Určitě chcete tento převod rozdělit?"
  },
  "multiDelete": {
    "confirm": {
      "Content": "Jste si jisti, že chcete smazat <1>{n, plural, one{# transakci} few{# transakce} other{# transakcí}}</1>? Operace nelze stornovat",
      "OK": "Smazat {n, plural, one{# transakci} few{# transakce} other{# transakcí}}",
      "Title": "Odstranění označených transakcí"
    }
  },
  "page": {
    "title": "Transakce"
  },
  "table": {
    "button": {
      "ConfigureTable": "Přizpůsobit tabulku",
      "CreateCopy": "Vytvořte kopii",
      "MoreTransactions": "Další transakce",
      "ShowReceipt": "Zobrazit účtenku",
      "SplitTransfer": "Rozdělit převod"
    },
    "content": {
      "NothingWasFound": "Žádné transakce"
    },
    "filter": {
      "account": {
        "label": {
          "SelectAccount": "Zvolte účet"
        }
      },
      "amount": {
        "label": {
          "Amount": "Uveďte částku"
        }
      },
      "category": {
        "label": {
          "SelectCategory": "Vyberte kategorii"
        }
      },
      "project": {
        "label": {
          "SelectProject": "Vyberte projekt"
        }
      },
      "type": {
        "label": {
          "Expenses": "Výdaje",
          "Incomes": "Příjmy",
          "Loans": "Dluhy",
          "Transfers": "Převody"
        }
      },
      "user": {
        "label": {
          "deleted": "odstraněn",
          "notInTeam": "není v týmu",
          "SelectUser": "Vyberte uživatele"
        }
      }
    },
    "head": {
      "config": {
        "DisplayAdaptive": "Adaptivní",
        "DisplayAlways": "Vždy",
        "DisplayExtraColumns": "Zvolte podmínky pro výstup dalších sloupců.",
        "DisplayNever": "Nikdy",
        "Title": "Nastavení tabulky"
      },
      "label": {
        "CategoryDescription": "Kategorie, Popis",
        "Remain": "Zůstatek"
      }
    }
  },
  "transferJoin": {
    "button": {
      "Join": "Sloučit do převodu"
    },
    "message": {
      "ChooseCommissionCategory": "Uveďte prosím kategorii pro vytvoření výdaje - komise:",
      "ThisCanBeDoneWithCommission": "To může být provedeno, pokud vytvoříte výdajovou transakci komise ve výši <1>{sum}</1>.",
      "YouAreGoingToJoinWhat": "Chcete kombinovat transakce s různými částkami:"
    }
  },
  "unconfirmed": {
    "EndTitle": "Běžné transakce",
    "Title": "Nepotvrzené transakce"
  }
}

=== cubux-net/web-v2-i18n/locales/uk/front/transactions.json
{
  "message": {
    "ConfirmDeleteTransaction": "Ви справді бажаєте видалити транзакцію? Цю операцію неможливо скасувати.",
    "ConfirmPlannedTransaction": "Ви справді бажаєте підтвердити транзакцію?",
    "ConfirmSplitTransaction": "Ви справді бажаєте розділити цей переказ?"
  },
  "multiDelete": {
    "confirm": {
      "Content": "Ви справді бажаєте видалити <1>{n, plural, one{# транзакцію} few{# транзакції} other{# транзакцій}}</1>? Цю операцію неможливо буде скасувати.",
      "OK": "Видалити {n, plural, one{# транзакцію} few{# транзакції} other{# транзакцій}}",
      "Title": "Видалення вибраних транзакцій"
    }
  },
  "page": {
    "title": "Транзакції"
  },
  "table": {
    "button": {
      "ConfigureTable": "Налаштувати таблицю",
      "CreateCopy": "Створити копію",
      "MoreTransactions": "Ще транзакції",
      "ShowReceipt": "Показати чек",
      "SplitTransfer": "Розділити переказ"
    },
    "content": {
      "NothingWasFound": "Немає транзакцій"
    },
    "filter": {
      "account": {
        "label": {
          "SelectAccount": "Виберіть рахунок"
        }
      },
      "amount": {
        "label": {
          "Amount": "Зазначте суму"
        }
      },
      "category": {
        "label": {
          "SelectCategory": "Виберіть категорію"
        }
      },
      "project": {
        "label": {
          "SelectProject": "Виберіть проєкт"
        }
      },
      "type": {
        "label": {
          "Expenses": "Витрати",
          "Incomes": "Доходи",
          "Loans": "Борги",
          "Transfers": "Перекази"
        }
      },
      "user": {
        "label": {
          "deleted": "видалений",
          "notInTeam": "поза командою",
          "SelectUser": "Виберіть користувача"
        }
      }
    },
    "head": {
      "config": {
        "DisplayAdaptive": "Адаптувати",
        "DisplayAlways": "Завжди",
        "DisplayExtraColumns": "Виберіть умови для відображення додаткових стовпців.",
        "DisplayNever": "Ніколи",
        "Title": "Налаштування таблиці"
      },
      "label": {
        "CategoryDescription": "Категорія, Опис",
        "Remain": "Залишок"
      }
    }
  },
  "transferJoin": {
    "button": {
      "Join": "Об'єднати в переказ"
    },
    "message": {
      "ChooseCommissionCategory": "Будь ласка, вкажіть категорію для створення витрати комісії:",
      "ThisCanBeDoneWithCommission": "Це можна зробити, створивши транзакцію (витрату) для комісії на суму <1>{sum}</1>.",
      "YouAreGoingToJoinWhat": "Бажаєте об'єднати в переказ транзакції з різними сумами:"
    }
  },
  "unconfirmed": {
    "EndTitle": "Звичайні транзакції",
    "Title": "Непідтверджені транзакції"
  }
}
