=== cubux-net/web-v2-i18n/schemas/front/ui.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "string": {
      "type": "string",
      "minLength": 1
    }
  },
  "type": "object",
  "properties": {
    "appStatus": {
      "type": "object",
      "properties": {
        "cent": {
          "type": "object",
          "properties": {
            "Disconnected": {
              "$ref": "#/$defs/string"
            },
            "DisconnectedExplanation": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Disconnected", "DisconnectedExplanation"]
        },
        "refresh": {
          "type": "object",
          "properties": {
            "NewAppAvailable": {
              "$ref": "#/$defs/string"
            },
            "NewAppAvailableExplanation": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["NewAppAvailable", "NewAppAvailableExplanation"]
        }
      },
      "required": ["cent", "refresh"]
    },
    "button": {
      "type": "object",
      "properties": {
        "Add": {
          "$ref": "#/$defs/string"
        },
        "Back": {
          "$ref": "#/$defs/string"
        },
        "Cancel": {
          "$ref": "#/$defs/string"
        },
        "ChooseIcon": {
          "$ref": "#/$defs/string"
        },
        "ChooseImage": {
          "$ref": "#/$defs/string"
        },
        "Close": {
          "$ref": "#/$defs/string"
        },
        "Confirm": {
          "$ref": "#/$defs/string"
        },
        "Copy": {
          "$ref": "#/$defs/string"
        },
        "Create": {
          "$ref": "#/$defs/string"
        },
        "Delete": {
          "$ref": "#/$defs/string"
        },
        "Details": {
          "$ref": "#/$defs/string"
        },
        "Edit": {
          "$ref": "#/$defs/string"
        },
        "ExportExcel": {
          "$ref": "#/$defs/string"
        },
        "ImportCsv": {
          "$ref": "#/$defs/string"
        },
        "Insert": {
          "$ref": "#/$defs/string"
        },
        "Next": {
          "$ref": "#/$defs/string"
        },
        "No": {
          "$ref": "#/$defs/string"
        },
        "OK": {
          "$ref": "#/$defs/string"
        },
        "Retry": {
          "$ref": "#/$defs/string"
        },
        "Save": {
          "$ref": "#/$defs/string"
        },
        "SelectAccount": {
          "$ref": "#/$defs/string"
        },
        "SelectPartner": {
          "$ref": "#/$defs/string"
        },
        "Yes": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "Add",
        "Back",
        "Cancel",
        "ChooseIcon",
        "ChooseImage",
        "Close",
        "Confirm",
        "Copy",
        "Create",
        "Delete",
        "Details",
        "Edit",
        "ExportExcel",
        "ImportCsv",
        "Insert",
        "Next",
        "No",
        "OK",
        "Retry",
        "Save",
        "SelectAccount",
        "SelectPartner",
        "Yes"
      ]
    },
    "check": {
      "type": "object",
      "properties": {
        "CheckAll": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["CheckAll"]
    },
    "currencyRateHint": {
      "type": "object",
      "properties": {
        "ExchangeCurrency": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["ExchangeCurrency"]
    },
    "date": {
      "type": "object",
      "properties": {
        "label": {
          "type": "object",
          "properties": {
            "SelectRange": {
              "$ref": "#/$defs/string"
            },
            "Today": {
              "$ref": "#/$defs/string"
            },
            "since": {
              "$ref": "#/$defs/string"
            },
            "until": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["SelectRange", "Today", "since", "until"]
        }
      },
      "required": ["label"]
    },
    "downgrade": {
      "type": "object",
      "properties": {
        "button": {
          "type": "object",
          "properties": {
            "Navigate": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Navigate"]
        },
        "message": {
          "type": "object",
          "properties": {
            "PleaseProvideUsAReason": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["PleaseProvideUsAReason"]
        },
        "subtitle": {
          "$ref": "#/$defs/string"
        },
        "title": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["button", "message", "subtitle", "title"]
    },
    "field": {
      "type": "object",
      "properties": {
        "MonthLimit": {
          "$ref": "#/$defs/string"
        },
        "MonthPlan": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["MonthLimit", "MonthPlan"]
    },
    "label": {
      "type": "object",
      "properties": {
        "AskAQuestion": {
          "$ref": "#/$defs/string"
        },
        "DownloadAt": {
          "$ref": "#/$defs/string"
        },
        "FoundATypo": {
          "$ref": "#/$defs/string"
        },
        "and": {
          "$ref": "#/$defs/string"
        },
        "date": {
          "type": "object",
          "properties": {
            "sinceStart": {
              "$ref": "#/$defs/string"
            },
            "untilEnd": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["sinceStart", "untilEnd"]
        }
      },
      "required": ["AskAQuestion", "DownloadAt", "FoundATypo", "and", "date"]
    },
    "message": {
      "type": "object",
      "properties": {
        "CautionAboutDataLoss": {
          "$ref": "#/$defs/string"
        },
        "CheckFormAndFixErrors": {
          "$ref": "#/$defs/string"
        },
        "CouldNotPerformOperation": {
          "$ref": "#/$defs/string"
        },
        "Done": {
          "$ref": "#/$defs/string"
        },
        "NoRecords": {
          "$ref": "#/$defs/string"
        },
        "NothingWasFound": {
          "$ref": "#/$defs/string"
        },
        "PleaseWait": {
          "$ref": "#/$defs/string"
        },
        "TemporaryDisabled": {
          "$ref": "#/$defs/string"
        },
        "ThisActionCannotBeUndone": {
          "$ref": "#/$defs/string"
        },
        "UncaughtErrorExplanation": {
          "$ref": "#/$defs/string"
        },
        "UnknownError": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "CautionAboutDataLoss",
        "CheckFormAndFixErrors",
        "CouldNotPerformOperation",
        "Done",
        "NoRecords",
        "NothingWasFound",
        "PleaseWait",
        "TemporaryDisabled",
        "ThisActionCannotBeUndone",
        "UncaughtErrorExplanation",
        "UnknownError"
      ]
    },
    "placeholder": {
      "type": "object",
      "properties": {
        "Search": {
          "$ref": "#/$defs/string"
        },
        "SelectCountry": {
          "$ref": "#/$defs/string"
        },
        "SelectCryptExchanger": {
          "$ref": "#/$defs/string"
        },
        "SelectCurrency": {
          "$ref": "#/$defs/string"
        },
        "SelectDate": {
          "$ref": "#/$defs/string"
        },
        "SelectLanguage": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "Search",
        "SelectCountry",
        "SelectCryptExchanger",
        "SelectCurrency",
        "SelectDate",
        "SelectLanguage"
      ]
    },
    "select": {
      "type": "object",
      "properties": {
        "UseDefault": {
          "$ref": "#/$defs/string"
        },
        "payInterval": {
          "type": "object",
          "properties": {
            "Empty": {
              "$ref": "#/$defs/string"
            },
            "m": {
              "$ref": "#/$defs/string"
            },
            "q": {
              "$ref": "#/$defs/string"
            },
            "w": {
              "$ref": "#/$defs/string"
            }
          },
          "required": ["Empty", "m", "q", "w"]
        }
      },
      "required": ["UseDefault", "payInterval"]
    },
    "state": {
      "type": "object",
      "properties": {
        "Error": {
          "$ref": "#/$defs/string"
        },
        "Loading": {
          "$ref": "#/$defs/string"
        }
      },
      "required": ["Error", "Loading"]
    }
  },
  "required": [
    "appStatus",
    "button",
    "check",
    "currencyRateHint",
    "date",
    "downgrade",
    "field",
    "label",
    "message",
    "placeholder",
    "select",
    "state"
  ]
}

=== cubux-net/web-v2-i18n/locales/ru/front/ui.json
{
  "appStatus": {
    "cent": {
      "Disconnected": "Соединение прервано",
      "DisconnectedExplanation": "Потеряно соединение с сервером. Некоторые процессы могут работать некорректно или не работать вовсе. Проверьте подключение к сети Интернет. Если вы уверены, что подключение в порядке, но ошибка проявляется длительное время, обратитесь к нам в поддержку."
    },
    "refresh": {
      "NewAppAvailable": "Доступна новая версия",
      "NewAppAvailableExplanation": "Доступна новая версия. <1>Обновить страницу</1>"
    }
  },
  "button": {
    "Add": "Добавить",
    "Back": "Назад",
    "Cancel": "Отмена",
    "ChooseIcon": "Выбрать иконку",
    "ChooseImage": "Выбрать изображение",
    "Close": "Закрыть",
    "Confirm": "Подтвердить",
    "Copy": "Копировать",
    "Create": "Создать",
    "Delete": "Удалить",
    "Details": "Подробнее",
    "Edit": "Редактировать",
    "ExportExcel": "Экспорт в Excel",
    "ImportCsv": "Импорт CSV",
    "Insert": "Вставить",
    "Next": "Далее",
    "No": "Нет",
    "OK": "OK",
    "Retry": "Повторить",
    "Save": "Сохранить",
    "SelectAccount": "Выберите счет",
    "SelectPartner": "Выберите контрагента",
    "Yes": "Да"
  },
  "check": {
    "CheckAll": "Выбрать все"
  },
  "currencyRateHint": {
    "ExchangeCurrency": "Обмен по курсу"
  },
  "date": {
    "label": {
      "SelectRange": "Выберите диапазон",
      "since": "с",
      "Today": "Сегодня",
      "until": "по"
    }
  },
  "downgrade": {
    "button": {
      "Navigate": "Перейти"
    },
    "message": {
      "PleaseProvideUsAReason": "Пожалуйста, укажите причину, чтобы мы могли улучшить на сервис."
    },
    "subtitle": "Это поможет стать нам лучше.",
    "title": "Напишите, что вам не понравилось?"
  },
  "field": {
    "MonthLimit": "Лимит в месяц",
    "MonthPlan": "План в месяц"
  },
  "label": {
    "and": "и",
    "AskAQuestion": "Задать вопрос",
    "date": {
      "sinceStart": "с начала",
      "untilEnd": "до конца"
    },
    "DownloadAt": "Скачать в",
    "FoundATypo": "Нашли опечатку?"
  },
  "message": {
    "CautionAboutDataLoss": "ПРЕДУПРЕЖДЕНИЕ О ПОТЕРЕ ДАННЫХ!",
    "CheckFormAndFixErrors": "Проверьте правильность заполнения полей и исправьте ошибки.",
    "CouldNotPerformOperation": "Не удалось выполнить операцию.",
    "Done": "Готово.",
    "NoRecords": "Ничего нет.",
    "NothingWasFound": "Ничего не найдено.",
    "PleaseWait": "Пожалуйста, подождите...",
    "TemporaryDisabled": "Временно отключено.",
    "ThisActionCannotBeUndone": "Это действие нельзя будет отменить.",
    "UncaughtErrorExplanation": "Извините, произошла ошибка. Для начала попробуйте <1>обновить страницу</1>. Если это не помогло, проверьте интернет соединение и настройки прокси. Если и это не помогло, обратитесь в нашу службу поддержки.",
    "UnknownError": "Неизвестная ошибка."
  },
  "placeholder": {
    "Search": "Поиск",
    "SelectCountry": "Выберите страну",
    "SelectCryptExchanger": "Выберите биржу криптовалют",
    "SelectCurrency": "Выберите валюту",
    "SelectDate": "Выберите дату",
    "SelectLanguage": "Выберите язык"
  },
  "select": {
    "payInterval": {
      "Empty": "Вручную",
      "m": "1 раз в месяц",
      "q": "1 раз в квартал",
      "w": "1 раз в неделю"
    },
    "UseDefault": "Использовать по умолчанию"
  },
  "state": {
    "Error": "Ошибка",
    "Loading": "Загрузка..."
  }
}

=== cubux-net/web-v2-i18n/locales/en/front/ui.json
{
  "appStatus": {
    "cent": {
      "Disconnected": "Connection lost",
      "DisconnectedExplanation": "Connection with server lost. Something can work incorrect or not work at all. Check you Internet connection. If you are sure you internet connection is fine, but the error still happens a long time, feel free to contact our support system."
    },
    "refresh": {
      "NewAppAvailable": "New version available",
      "NewAppAvailableExplanation": "A new version available. <1>Refresh page</1>"
    }
  },
  "button": {
    "Add": "Add",
    "Back": "Back",
    "Cancel": "Cancel",
    "ChooseIcon": "Choose icon",
    "ChooseImage": "Choose image",
    "Close": "Close",
    "Confirm": "Confirm",
    "Copy": "Copy",
    "Create": "Create",
    "Delete": "Delete",
    "Details": "Details",
    "Edit": "Edit",
    "ExportExcel": "Export to Excel",
    "ImportCsv": "Import CSV",
    "Insert": "Insert",
    "Next": "Next",
    "No": "No",
    "OK": "OK",
    "Retry": "Retry",
    "Save": "Save",
    "SelectAccount": "Select account",
    "SelectPartner": "Select partner",
    "Yes": "Yes"
  },
  "check": {
    "CheckAll": "Check all"
  },
  "currencyRateHint": {
    "ExchangeCurrency": "Exchange rate"
  },
  "date": {
    "label": {
      "SelectRange": "Select a range",
      "since": "since",
      "Today": "Today",
      "until": "until"
    }
  },
  "downgrade": {
    "button": {
      "Navigate": "Navigate"
    },
    "message": {
      "PleaseProvideUsAReason": "Please provide us a reason, so we would make our service better."
    },
    "subtitle": "It will help us to became better.",
    "title": "Write us what did you dislike?"
  },
  "field": {
    "MonthLimit": "Month limit",
    "MonthPlan": "Month plan"
  },
  "label": {
    "and": "and",
    "AskAQuestion": "Ask a question",
    "date": {
      "sinceStart": "start",
      "untilEnd": "end"
    },
    "DownloadAt": "Download at",
    "FoundATypo": "Found a typo?"
  },
  "message": {
    "CautionAboutDataLoss": "CAUTION ABOUT DATA LOSS!",
    "CheckFormAndFixErrors": "Check data correctness and fix errors.",
    "CouldNotPerformOperation": "Couldn't perform operation.",
    "Done": "Done",
    "NoRecords": "Nothing here.",
    "NothingWasFound": "Nothing was found.",
    "PleaseWait": "Please, wait...",
    "TemporaryDisabled": "Temporary disabled.",
    "ThisActionCannotBeUndone": "This action cannot be undone",
    "UncaughtErrorExplanation": "Sorry, an error occurred. Try to <1>reload page</1> first. If it didn't help, check internet connection and proxy settings. If it didn't help too, contact out support system.",
    "UnknownError": "Unknown error."
  },
  "placeholder": {
    "Search": "Search",
    "SelectCountry": "Select country",
    "SelectCryptExchanger": "Select crypt exchanger",
    "SelectCurrency": "Select currency",
    "SelectDate": "Select date",
    "SelectLanguage": "Select language"
  },
  "select": {
    "payInterval": {
      "Empty": "none",
      "m": "every month",
      "q": "every quarter",
      "w": "every week"
    },
    "UseDefault": "Use default"
  },
  "state": {
    "Error": "Error",
    "Loading": "Loading..."
  }
}
